// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: courses.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (slug, title, price)
VALUES (?, ?, ?)
RETURNING id, slug, title, price
`

type CreateCourseParams struct {
	Slug  string `json:"slug"`
	Title string `json:"title"`
	Price int64  `json:"price"`
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRowContext(ctx, createCourse, arg.Slug, arg.Title, arg.Price)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Price,
	)
	return i, err
}

const deleteCourse = `-- name: DeleteCourse :exec
DELETE FROM courses
WHERE id = ?
`

func (q *Queries) DeleteCourse(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCourse, id)
	return err
}

const findCoursesByIDs = `-- name: FindCoursesByIDs :many
SELECT id, slug, title, price FROM courses
WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) FindCoursesByIDs(ctx context.Context, ids []int64) ([]Course, error) {
	query := findCoursesByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCourse = `-- name: GetCourse :one
SELECT id, slug, title, price FROM courses
WHERE id = ?
`

func (q *Queries) GetCourse(ctx context.Context, id int64) (Course, error) {
	row := q.db.QueryRowContext(ctx, getCourse, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Price,
	)
	return i, err
}

const getCourseBySlug = `-- name: GetCourseBySlug :one
SELECT id, slug, title, price FROM courses
WHERE slug = ?
`

func (q *Queries) GetCourseBySlug(ctx context.Context, slug string) (Course, error) {
	row := q.db.QueryRowContext(ctx, getCourseBySlug, slug)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Price,
	)
	return i, err
}

const listCourses = `-- name: ListCourses :many
SELECT id, slug, title, price FROM courses
ORDER BY id
`

func (q *Queries) ListCourses(ctx context.Context) ([]Course, error) {
	rows, err := q.db.QueryContext(ctx, listCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCourse = `-- name: UpdateCourse :exec
UPDATE courses
SET title = COALESCE(?2, title),
    price = COALESCE(?3, price)
WHERE id = ?
`

type UpdateCourseParams struct {
	Title sql.NullString `json:"title"`
	Price sql.NullInt64  `json:"price"`
	ID    int64          `json:"id"`
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) error {
	_, err := q.db.ExecContext(ctx, updateCourse, arg.Title, arg.Price, arg.ID)
	return err
}

const upsertCourse = `-- name: UpsertCourse :exec
INSERT INTO courses (slug, title, price)
VALUES (?, ?, ?)
ON CONFLICT(slug) DO UPDATE SET
    title = excluded.title,
    price = excluded.price
`

type UpsertCourseParams struct {
	Slug  string `json:"slug"`
	Title string `json:"title"`
	Price int64  `json:"price"`
}

func (q *Queries) UpsertCourse(ctx context.Context, arg UpsertCourseParams) error {
	_, err := q.db.ExecContext(ctx, upsertCourse, arg.Slug, arg.Title, arg.Price)
	return err
}
