// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: courses_write.sql

package db

import (
	"context"
	"database/sql"
)

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (slug, title, price)
VALUES (?, ?, ?)
RETURNING id, slug, title, price
`

type CreateCourseParams struct {
	Slug  string `json:"slug"`
	Title string `json:"title"`
	Price int64  `json:"price"`
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRowContext(ctx, createCourse, arg.Slug, arg.Title, arg.Price)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Price,
	)
	return i, err
}

const deleteCourse = `-- name: DeleteCourse :exec
DELETE FROM courses
WHERE id = ?
`

func (q *Queries) DeleteCourse(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCourse, id)
	return err
}

const updateCourse = `-- name: UpdateCourse :exec
UPDATE courses
SET title = COALESCE(?2, title),
    price = COALESCE(?3, price)
WHERE id = ?
`

type UpdateCourseParams struct {
	Title sql.NullString `json:"title"`
	Price sql.NullInt64  `json:"price"`
	ID    int64          `json:"id"`
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) error {
	_, err := q.db.ExecContext(ctx, updateCourse, arg.Title, arg.Price, arg.ID)
	return err
}

const upsertCourse = `-- name: UpsertCourse :exec
INSERT INTO courses (slug, title, price)
VALUES (?, ?, ?)
ON CONFLICT(slug) DO UPDATE SET
    title = excluded.title,
    price = excluded.price
`

type UpsertCourseParams struct {
	Slug  string `json:"slug"`
	Title string `json:"title"`
	Price int64  `json:"price"`
}

func (q *Queries) UpsertCourse(ctx context.Context, arg UpsertCourseParams) error {
	_, err := q.db.ExecContext(ctx, upsertCourse, arg.Slug, arg.Title, arg.Price)
	return err
}
