// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: courses_read.sql

package db

import (
	"context"
	"strings"
)

const countCourses = `-- name: CountCourses :one
SELECT COUNT(*) FROM courses
`

func (q *Queries) CountCourses(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCourses)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findCoursesByIDs = `-- name: FindCoursesByIDs :many
SELECT id, slug, title, price FROM courses
WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) FindCoursesByIDs(ctx context.Context, ids []int64) ([]Course, error) {
	query := findCoursesByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCourse = `-- name: GetCourse :one
SELECT id, slug, title, price FROM courses
WHERE id = ?
`

func (q *Queries) GetCourse(ctx context.Context, id int64) (Course, error) {
	row := q.db.QueryRowContext(ctx, getCourse, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Price,
	)
	return i, err
}

const getCourseBySlug = `-- name: GetCourseBySlug :one
SELECT id, slug, title, price FROM courses
WHERE slug = ?
`

func (q *Queries) GetCourseBySlug(ctx context.Context, slug string) (Course, error) {
	row := q.db.QueryRowContext(ctx, getCourseBySlug, slug)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Price,
	)
	return i, err
}

const getCourseWithEnrollments = `-- name: GetCourseWithEnrollments :one
WITH enrollment_list AS (
    SELECT
        e.course_id,
        json_group_array(json_object(
            'id', e.id,
            'user_id', e.user_id,
            'user_email', COALESCE(u.email, ''),
            'user_name', u.name,
            'enrolled_at', e.enrolled_at,
            'status', e.status
        )) AS payload
    FROM enrollments e
    LEFT JOIN users u ON e.user_id = u.id
    WHERE e.course_id = ?
)
SELECT
    c.id,
    c.slug,
    c.title,
    c.price,
    COALESCE(el.payload, '[]') AS enrollments
FROM courses c
LEFT JOIN enrollment_list el ON el.course_id = c.id
WHERE c.id = ?
`

type GetCourseWithEnrollmentsParams struct {
	CourseID int64 `json:"course_id"`
	ID       int64 `json:"id"`
}

type GetCourseWithEnrollmentsRow struct {
	ID          int64       `json:"id"`
	Slug        string      `json:"slug"`
	Title       string      `json:"title"`
	Price       int64       `json:"price"`
	Enrollments interface{} `json:"enrollments"`
}

func (q *Queries) GetCourseWithEnrollments(ctx context.Context, arg GetCourseWithEnrollmentsParams) (GetCourseWithEnrollmentsRow, error) {
	row := q.db.QueryRowContext(ctx, getCourseWithEnrollments, arg.CourseID, arg.ID)
	var i GetCourseWithEnrollmentsRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Price,
		&i.Enrollments,
	)
	return i, err
}

const listCourses = `-- name: ListCourses :many
SELECT id, slug, title, price
FROM courses
ORDER BY id
LIMIT ? OFFSET ?
`

type ListCoursesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListCourses(ctx context.Context, arg ListCoursesParams) ([]Course, error) {
	rows, err := q.db.QueryContext(ctx, listCourses, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
