// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enrollments.sql

package db

import (
	"context"
	"database/sql"
)

const checkCourseExists = `-- name: CheckCourseExists :one
SELECT 1 FROM courses WHERE id = ?
`

func (q *Queries) CheckCourseExists(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkCourseExists, id)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const checkUserExists = `-- name: CheckUserExists :one
SELECT 1 FROM users WHERE id = ?
`

func (q *Queries) CheckUserExists(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkUserExists, id)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createEnrollment = `-- name: CreateEnrollment :one
INSERT INTO enrollments (user_id, course_id, status)
VALUES (?, ?, ?)
RETURNING id, user_id, course_id, enrolled_at, status
`

type CreateEnrollmentParams struct {
	UserID   int64  `json:"user_id"`
	CourseID int64  `json:"course_id"`
	Status   string `json:"status"`
}

func (q *Queries) CreateEnrollment(ctx context.Context, arg CreateEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRowContext(ctx, createEnrollment, arg.UserID, arg.CourseID, arg.Status)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourseID,
		&i.EnrolledAt,
		&i.Status,
	)
	return i, err
}

const getEnrollment = `-- name: GetEnrollment :one
SELECT id, user_id, course_id, enrolled_at, status FROM enrollments
WHERE id = ?
`

func (q *Queries) GetEnrollment(ctx context.Context, id int64) (Enrollment, error) {
	row := q.db.QueryRowContext(ctx, getEnrollment, id)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourseID,
		&i.EnrolledAt,
		&i.Status,
	)
	return i, err
}

const getEnrollmentByUserAndCourse = `-- name: GetEnrollmentByUserAndCourse :one
SELECT id, user_id, course_id, enrolled_at, status FROM enrollments
WHERE user_id = ? AND course_id = ?
`

type GetEnrollmentByUserAndCourseParams struct {
	UserID   int64 `json:"user_id"`
	CourseID int64 `json:"course_id"`
}

func (q *Queries) GetEnrollmentByUserAndCourse(ctx context.Context, arg GetEnrollmentByUserAndCourseParams) (Enrollment, error) {
	row := q.db.QueryRowContext(ctx, getEnrollmentByUserAndCourse, arg.UserID, arg.CourseID)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourseID,
		&i.EnrolledAt,
		&i.Status,
	)
	return i, err
}

const listEnrollments = `-- name: ListEnrollments :many
SELECT 
    e.id,
    e.user_id,
    u.email as user_email,
    u.name as user_name,
    e.course_id,
    c.slug as course_slug,
    c.title as course_title,
    e.enrolled_at,
    e.status
FROM enrollments e
JOIN users u ON e.user_id = u.id
JOIN courses c ON e.course_id = c.id
ORDER BY e.enrolled_at DESC
`

type ListEnrollmentsRow struct {
	ID          int64          `json:"id"`
	UserID      int64          `json:"user_id"`
	UserEmail   string         `json:"user_email"`
	UserName    sql.NullString `json:"user_name"`
	CourseID    int64          `json:"course_id"`
	CourseSlug  string         `json:"course_slug"`
	CourseTitle string         `json:"course_title"`
	EnrolledAt  sql.NullTime   `json:"enrolled_at"`
	Status      string         `json:"status"`
}

func (q *Queries) ListEnrollments(ctx context.Context) ([]ListEnrollmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEnrollments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnrollmentsRow
	for rows.Next() {
		var i ListEnrollmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserEmail,
			&i.UserName,
			&i.CourseID,
			&i.CourseSlug,
			&i.CourseTitle,
			&i.EnrolledAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnrollmentsByCourse = `-- name: ListEnrollmentsByCourse :many
SELECT 
    e.id,
    e.user_id,
    u.email as user_email,
    u.name as user_name,
    e.course_id,
    c.slug as course_slug,
    c.title as course_title,
    e.enrolled_at,
    e.status
FROM enrollments e
JOIN users u ON e.user_id = u.id
JOIN courses c ON e.course_id = c.id
WHERE e.course_id = ?
ORDER BY e.enrolled_at DESC
`

type ListEnrollmentsByCourseRow struct {
	ID          int64          `json:"id"`
	UserID      int64          `json:"user_id"`
	UserEmail   string         `json:"user_email"`
	UserName    sql.NullString `json:"user_name"`
	CourseID    int64          `json:"course_id"`
	CourseSlug  string         `json:"course_slug"`
	CourseTitle string         `json:"course_title"`
	EnrolledAt  sql.NullTime   `json:"enrolled_at"`
	Status      string         `json:"status"`
}

func (q *Queries) ListEnrollmentsByCourse(ctx context.Context, courseID int64) ([]ListEnrollmentsByCourseRow, error) {
	rows, err := q.db.QueryContext(ctx, listEnrollmentsByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnrollmentsByCourseRow
	for rows.Next() {
		var i ListEnrollmentsByCourseRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserEmail,
			&i.UserName,
			&i.CourseID,
			&i.CourseSlug,
			&i.CourseTitle,
			&i.EnrolledAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnrollmentsByUser = `-- name: ListEnrollmentsByUser :many
SELECT 
    e.id,
    e.user_id,
    u.email as user_email,
    u.name as user_name,
    e.course_id,
    c.slug as course_slug,
    c.title as course_title,
    e.enrolled_at,
    e.status
FROM enrollments e
JOIN users u ON e.user_id = u.id
JOIN courses c ON e.course_id = c.id
WHERE e.user_id = ?
ORDER BY e.enrolled_at DESC
`

type ListEnrollmentsByUserRow struct {
	ID          int64          `json:"id"`
	UserID      int64          `json:"user_id"`
	UserEmail   string         `json:"user_email"`
	UserName    sql.NullString `json:"user_name"`
	CourseID    int64          `json:"course_id"`
	CourseSlug  string         `json:"course_slug"`
	CourseTitle string         `json:"course_title"`
	EnrolledAt  sql.NullTime   `json:"enrolled_at"`
	Status      string         `json:"status"`
}

func (q *Queries) ListEnrollmentsByUser(ctx context.Context, userID int64) ([]ListEnrollmentsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listEnrollmentsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnrollmentsByUserRow
	for rows.Next() {
		var i ListEnrollmentsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserEmail,
			&i.UserName,
			&i.CourseID,
			&i.CourseSlug,
			&i.CourseTitle,
			&i.EnrolledAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnrollmentStatus = `-- name: UpdateEnrollmentStatus :exec
UPDATE enrollments
SET status = ?
WHERE user_id = ? AND course_id = ? AND status = 'active'
`

type UpdateEnrollmentStatusParams struct {
	Status   string `json:"status"`
	UserID   int64  `json:"user_id"`
	CourseID int64  `json:"course_id"`
}

func (q *Queries) UpdateEnrollmentStatus(ctx context.Context, arg UpdateEnrollmentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateEnrollmentStatus, arg.Status, arg.UserID, arg.CourseID)
	return err
}
