// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enrollments_write.sql

package db

import (
	"context"
)

const createEnrollment = `-- name: CreateEnrollment :one
INSERT INTO enrollments (user_id, course_id, status)
VALUES (?, ?, ?)
RETURNING id, user_id, course_id, enrolled_at, status
`

type CreateEnrollmentParams struct {
	UserID   int64  `json:"user_id"`
	CourseID int64  `json:"course_id"`
	Status   string `json:"status"`
}

func (q *Queries) CreateEnrollment(ctx context.Context, arg CreateEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRowContext(ctx, createEnrollment, arg.UserID, arg.CourseID, arg.Status)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourseID,
		&i.EnrolledAt,
		&i.Status,
	)
	return i, err
}

const updateEnrollmentStatus = `-- name: UpdateEnrollmentStatus :exec
UPDATE enrollments
SET status = ?
WHERE user_id = ? AND course_id = ? AND status = 'active'
`

type UpdateEnrollmentStatusParams struct {
	Status   string `json:"status"`
	UserID   int64  `json:"user_id"`
	CourseID int64  `json:"course_id"`
}

func (q *Queries) UpdateEnrollmentStatus(ctx context.Context, arg UpdateEnrollmentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateEnrollmentStatus, arg.Status, arg.UserID, arg.CourseID)
	return err
}
