// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Course struct {
	ID    int64  `json:"id"`
	Slug  string `json:"slug"`
	Title string `json:"title"`
	Price int64  `json:"price"`
}

type Enrollment struct {
	ID         int64        `json:"id"`
	UserID     int64        `json:"user_id"`
	CourseID   int64        `json:"course_id"`
	EnrolledAt sql.NullTime `json:"enrolled_at"`
	Status     string       `json:"status"`
}

type User struct {
	ID        int64          `json:"id"`
	Email     string         `json:"email"`
	Name      sql.NullString `json:"name"`
	Age       sql.NullInt64  `json:"age"`
	CreatedAt sql.NullTime   `json:"created_at"`
}
