// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders_read.sql

package db

import (
	"context"
	"database/sql"
)

const checkUserOwnsCourse = `-- name: CheckUserOwnsCourse :one
SELECT EXISTS(
    SELECT 1
    FROM enrollments e
    WHERE e.user_id = ?
      AND e.course_id = ?
      AND e.status = 'active'
) as owns_course
`

type CheckUserOwnsCourseParams struct {
	UserID   int64 `json:"user_id"`
	CourseID int64 `json:"course_id"`
}

// Check if user owns a course by looking at enrollments
// This includes both purchased courses (with order_id) and free courses (without order_id)
func (q *Queries) CheckUserOwnsCourse(ctx context.Context, arg CheckUserOwnsCourseParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkUserOwnsCourse, arg.UserID, arg.CourseID)
	var owns_course bool
	err := row.Scan(&owns_course)
	return owns_course, err
}

const getCourseRevenue = `-- name: GetCourseRevenue :one
SELECT 
    c.id,
    c.slug,
    c.title,
    COUNT(oi.id) as sales_count,
    COALESCE(SUM(oi.price), 0) as total_revenue
FROM courses c
LEFT JOIN order_items oi ON oi.course_id = c.id
LEFT JOIN orders o ON o.id = oi.order_id AND o.status = 'completed'
WHERE c.id = ?
GROUP BY c.id
`

type GetCourseRevenueRow struct {
	ID           int64       `json:"id"`
	Slug         string      `json:"slug"`
	Title        string      `json:"title"`
	SalesCount   int64       `json:"sales_count"`
	TotalRevenue interface{} `json:"total_revenue"`
}

func (q *Queries) GetCourseRevenue(ctx context.Context, id int64) (GetCourseRevenueRow, error) {
	row := q.db.QueryRowContext(ctx, getCourseRevenue, id)
	var i GetCourseRevenueRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.SalesCount,
		&i.TotalRevenue,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, user_id, total_amount, status, payment_method, created_at, completed_at FROM orders WHERE id = ?
`

func (q *Queries) GetOrder(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalAmount,
		&i.Status,
		&i.PaymentMethod,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getOrderWithItems = `-- name: GetOrderWithItems :one
WITH items_data AS (
    SELECT 
        oi.order_id,
        json_group_array(json_object(
            'id', oi.id,
            'course_id', oi.course_id,
            'course_slug', COALESCE(c.slug, ''),
            'course_title', COALESCE(c.title, ''),
            'price', oi.price,
            'created_at', oi.created_at
        )) as items
    FROM order_items oi
    LEFT JOIN courses c ON c.id = oi.course_id
    WHERE oi.order_id = ?
)
SELECT 
    o.id,
    o.user_id,
    o.total_amount,
    o.status,
    o.payment_method,
    o.created_at,
    o.completed_at,
    COALESCE(i.items, '[]') as items
FROM orders o
LEFT JOIN items_data i ON i.order_id = o.id
WHERE o.id = ?
`

type GetOrderWithItemsParams struct {
	OrderID int64 `json:"order_id"`
	ID      int64 `json:"id"`
}

type GetOrderWithItemsRow struct {
	ID            int64          `json:"id"`
	UserID        int64          `json:"user_id"`
	TotalAmount   int64          `json:"total_amount"`
	Status        string         `json:"status"`
	PaymentMethod sql.NullString `json:"payment_method"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	CompletedAt   sql.NullTime   `json:"completed_at"`
	Items         interface{}    `json:"items"`
}

func (q *Queries) GetOrderWithItems(ctx context.Context, arg GetOrderWithItemsParams) (GetOrderWithItemsRow, error) {
	row := q.db.QueryRowContext(ctx, getOrderWithItems, arg.OrderID, arg.ID)
	var i GetOrderWithItemsRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalAmount,
		&i.Status,
		&i.PaymentMethod,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.Items,
	)
	return i, err
}

const getUserOrders = `-- name: GetUserOrders :many
WITH order_data AS (
    SELECT 
        o.id,
        o.user_id,
        o.total_amount,
        o.status,
        o.payment_method,
        o.created_at,
        o.completed_at,
        json_group_array(json_object(
            'id', oi.id,
            'course_id', oi.course_id,
            'course_slug', COALESCE(c.slug, ''),
            'course_title', COALESCE(c.title, ''),
            'price', oi.price
        )) as items
    FROM orders o
    LEFT JOIN order_items oi ON oi.order_id = o.id
    LEFT JOIN courses c ON c.id = oi.course_id
    WHERE o.user_id = ?
    GROUP BY o.id
)
SELECT id, user_id, total_amount, status, payment_method, created_at, completed_at, items FROM order_data
ORDER BY created_at DESC
`

type GetUserOrdersRow struct {
	ID            int64          `json:"id"`
	UserID        int64          `json:"user_id"`
	TotalAmount   int64          `json:"total_amount"`
	Status        string         `json:"status"`
	PaymentMethod sql.NullString `json:"payment_method"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	CompletedAt   sql.NullTime   `json:"completed_at"`
	Items         interface{}    `json:"items"`
}

func (q *Queries) GetUserOrders(ctx context.Context, userID int64) ([]GetUserOrdersRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserOrders, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserOrdersRow
	for rows.Next() {
		var i GetUserOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TotalAmount,
			&i.Status,
			&i.PaymentMethod,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.Items,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT id, user_id, total_amount, status, payment_method, created_at, completed_at FROM orders
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListOrdersParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrders, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TotalAmount,
			&i.Status,
			&i.PaymentMethod,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT id, user_id, total_amount, status, payment_method, created_at, completed_at FROM orders
WHERE user_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListOrdersByUser(ctx context.Context, userID int64) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TotalAmount,
			&i.Status,
			&i.PaymentMethod,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
