// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders_write.sql

package db

import (
	"context"
	"database/sql"
)

const completeOrder = `-- name: CompleteOrder :exec
UPDATE orders
SET status = 'completed', completed_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) CompleteOrder(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, completeOrder, id)
	return err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (user_id, total_amount, status, payment_method)
VALUES (?, ?, ?, ?)
RETURNING id, user_id, total_amount, status, payment_method, created_at, completed_at
`

type CreateOrderParams struct {
	UserID        int64          `json:"user_id"`
	TotalAmount   int64          `json:"total_amount"`
	Status        string         `json:"status"`
	PaymentMethod sql.NullString `json:"payment_method"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder,
		arg.UserID,
		arg.TotalAmount,
		arg.Status,
		arg.PaymentMethod,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalAmount,
		&i.Status,
		&i.PaymentMethod,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, course_id, price)
VALUES (?, ?, ?)
RETURNING id, order_id, course_id, price, created_at
`

type CreateOrderItemParams struct {
	OrderID  int64 `json:"order_id"`
	CourseID int64 `json:"course_id"`
	Price    int64 `json:"price"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, createOrderItem, arg.OrderID, arg.CourseID, arg.Price)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.CourseID,
		&i.Price,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOrder = `-- name: DeleteOrder :exec
DELETE FROM orders WHERE id = ?
`

func (q *Queries) DeleteOrder(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteOrder, id)
	return err
}

const failOrder = `-- name: FailOrder :exec
UPDATE orders
SET status = 'failed'
WHERE id = ?
`

func (q *Queries) FailOrder(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, failOrder, id)
	return err
}

const refundOrder = `-- name: RefundOrder :exec
UPDATE orders
SET status = 'refunded'
WHERE id = ?
`

func (q *Queries) RefundOrder(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, refundOrder, id)
	return err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET status = ?, completed_at = CASE WHEN ? = 'completed' THEN CURRENT_TIMESTAMP ELSE completed_at END
WHERE id = ?
`

type UpdateOrderStatusParams struct {
	Status  string      `json:"status"`
	Column2 interface{} `json:"column_2"`
	ID      int64       `json:"id"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderStatus, arg.Status, arg.Column2, arg.ID)
	return err
}
