// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CheckCourseExists(ctx context.Context, id int64) (int64, error)
	CheckUserExists(ctx context.Context, id int64) (int64, error)
	CountCourses(ctx context.Context) (int64, error)
	CountEnrollments(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error)
	CreateEnrollment(ctx context.Context, arg CreateEnrollmentParams) (Enrollment, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCourse(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteUsersByIDs(ctx context.Context, ids []int64) (int64, error)
	FindCoursesByIDs(ctx context.Context, ids []int64) ([]Course, error)
	GetCourse(ctx context.Context, id int64) (Course, error)
	GetCourseBySlug(ctx context.Context, slug string) (Course, error)
	GetEnrollment(ctx context.Context, id int64) (Enrollment, error)
	GetEnrollmentByUserAndCourse(ctx context.Context, arg GetEnrollmentByUserAndCourseParams) (Enrollment, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListCourses(ctx context.Context, arg ListCoursesParams) ([]Course, error)
	ListEnrollments(ctx context.Context, arg ListEnrollmentsParams) ([]ListEnrollmentsRow, error)
	ListEnrollmentsByCourse(ctx context.Context, courseID int64) ([]ListEnrollmentsByCourseRow, error)
	ListEnrollmentsByUser(ctx context.Context, userID int64) ([]ListEnrollmentsByUserRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateCourse(ctx context.Context, arg UpdateCourseParams) error
	UpdateEnrollmentStatus(ctx context.Context, arg UpdateEnrollmentStatusParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpsertCourse(ctx context.Context, arg UpsertCourseParams) error
	UpsertUser(ctx context.Context, arg UpsertUserParams) error
}

var _ Querier = (*Queries)(nil)
