// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CheckCourseExists(ctx context.Context, id int64) (int64, error)
	CheckUserExists(ctx context.Context, id int64) (int64, error)
	CheckUserOwnsCourse(ctx context.Context, arg CheckUserOwnsCourseParams) (bool, error)
	CompleteOrder(ctx context.Context, id int64) error
	CountCourses(ctx context.Context) (int64, error)
	CountEnrollments(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error)
	CreateEnrollment(ctx context.Context, arg CreateEnrollmentParams) (Enrollment, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCourse(ctx context.Context, id int64) error
	DeleteOrder(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteUsersByIDs(ctx context.Context, ids []int64) (int64, error)
	FailOrder(ctx context.Context, id int64) error
	FindCoursesByIDs(ctx context.Context, ids []int64) ([]Course, error)
	GetCourse(ctx context.Context, id int64) (Course, error)
	GetCourseBySlug(ctx context.Context, slug string) (Course, error)
	GetCourseRevenue(ctx context.Context, id int64) (GetCourseRevenueRow, error)
	GetCourseWithEnrollments(ctx context.Context, arg GetCourseWithEnrollmentsParams) (GetCourseWithEnrollmentsRow, error)
	GetEnrollment(ctx context.Context, id int64) (Enrollment, error)
	GetEnrollmentByUserAndCourse(ctx context.Context, arg GetEnrollmentByUserAndCourseParams) (Enrollment, error)
	GetOrder(ctx context.Context, id int64) (Order, error)
	GetOrderWithItems(ctx context.Context, arg GetOrderWithItemsParams) (GetOrderWithItemsRow, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserOrders(ctx context.Context, userID int64) ([]GetUserOrdersRow, error)
	ListCourses(ctx context.Context, arg ListCoursesParams) ([]Course, error)
	ListEnrollments(ctx context.Context, arg ListEnrollmentsParams) ([]ListEnrollmentsRow, error)
	ListEnrollmentsByCourse(ctx context.Context, courseID int64) ([]ListEnrollmentsByCourseRow, error)
	ListEnrollmentsByUser(ctx context.Context, userID int64) ([]ListEnrollmentsByUserRow, error)
	ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error)
	ListOrdersByUser(ctx context.Context, userID int64) ([]Order, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	RefundOrder(ctx context.Context, id int64) error
	UpdateCourse(ctx context.Context, arg UpdateCourseParams) error
	UpdateEnrollmentStatus(ctx context.Context, arg UpdateEnrollmentStatusParams) error
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpsertCourse(ctx context.Context, arg UpsertCourseParams) error
	UpsertUser(ctx context.Context, arg UpsertUserParams) error
}

var _ Querier = (*Queries)(nil)
