// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users_write.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name, age)
VALUES (?, ?, ?)
RETURNING id, email, name, age, created_at
`

type CreateUserParams struct {
	Email string         `json:"email"`
	Name  sql.NullString `json:"name"`
	Age   sql.NullInt64  `json:"age"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.Name, arg.Age)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Age,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const deleteUsersByIDs = `-- name: DeleteUsersByIDs :execrows
DELETE FROM users
WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) DeleteUsersByIDs(ctx context.Context, ids []int64) (int64, error) {
	query := deleteUsersByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	result, err := q.db.ExecContext(ctx, query, queryParams...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET name = COALESCE(?2, name),
    age = COALESCE(?3, age)
WHERE id = ?
`

type UpdateUserParams struct {
	Name sql.NullString `json:"name"`
	Age  sql.NullInt64  `json:"age"`
	ID   int64          `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser, arg.Name, arg.Age, arg.ID)
	return err
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users (email, name, age)
VALUES (?, ?, ?)
ON CONFLICT(email) DO UPDATE SET
    name = excluded.name,
    age = excluded.age
`

type UpsertUserParams struct {
	Email string         `json:"email"`
	Name  sql.NullString `json:"name"`
	Age   sql.NullInt64  `json:"age"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.ExecContext(ctx, upsertUser, arg.Email, arg.Name, arg.Age)
	return err
}
